# Generated by Django 3.0.7 on 2020-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=13)),
            ],
        ),
    ]
